// Generated by CoffeeScript 1.8.0
var FizzBuzzer, React;

React = require('react');

FizzBuzzer = React.createClass({
  getInitialState: function() {
    return {
      count: 0,
      display: 0
    };
  },
  increment: function() {
    var currentCount;
    this.setState({
      count: ++this.state.count
    });
    currentCount = this.state.count;
    if (this.isDivisibleByBoth(currentCount)) {
      return this.setState({
        display: 'FizzBuzz'
      });
    } else if (this.isDivisibleBy3(currentCount)) {
      return this.setState({
        display: 'Fizz'
      });
    } else if (this.isDivisibleBy5(currentCount)) {
      return this.setState({
        display: 'Buzz'
      });
    } else {
      return this.setState({
        display: currentCount
      });
    }
  },
  render: function() {
    var button, div, h1, _ref;
    _ref = React.DOM, div = _ref.div, h1 = _ref.h1, button = _ref.button;
    return div({}, [
      h1({}, this.state.display), button({
        onClick: this.increment
      }, 'Increment')
    ]);
  },
  isDivisibleBy3: function(number) {
    return number % 3 === 0;
  },
  isDivisibleBy5: function(number) {
    return number % 5 === 0;
  },
  isDivisibleByBoth: function(number) {
    return number % 5 === 0 && number % 3 === 0;
  }
});

React.render(React.createElement(FizzBuzzer, null), document.body);
